.TH AUTORENAMER 1 "November 27, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
autorenamer \- program to rename files so they sort according to given ordering
.SH SYNOPSIS
.B autorenamer
.SH DESCRIPTION
.B autorenamer
is an interactive graphical user interface program. It displays contents of a
directory using icons that you can reorder using drag-and-drop.  Once you are
done, the program renames the files such that their alphabetical ordering is
the same as the order you chose.
.P
If any entries are selected when "Save" is clicked, only the selected entries
are renamed. Otherwise all the entries in the directory are renamed.
.SH SEE ALSO
.BR mv (1).
.br
.SH AUTHOR
autorenamer was written by Marcin Owsiany <porridge@debian.org>.
